name: "setup-sqlite-action"

author: "ryohidaka"

description: "Custom action to set up SQLite environment."

inputs:
  version:
    description: "SQLite version to install (optional)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Check available SQLite versions
      id: check-versions
      run: |
        sudo apt-get update
        available_versions=$(apt-cache showpkg sqlite3 | grep -Eo '3\.[0-9]+\.[0-9]+' | sort -V | uniq | tr '\n' ',')
        available_versions=${available_versions%,}
        echo "Available versions: $available_versions"
        echo "versions=$available_versions" >> $GITHUB_OUTPUT
      shell: bash

    - name: Install specified SQLite version
      if: inputs.version != ''
      run: |
        if echo "${{ steps.check-versions.outputs.versions }}" | grep -q "^${{ inputs.version }}$"; then
          echo "Installing SQLite version ${{ inputs.version }}"
          sudo apt-get install -y sqlite3=${{ inputs.version }} libsqlite3-dev=${{ inputs.version }}
          echo "SQLite version ${{ inputs.version }} installed successfully."
        else
          echo "Error: Specified version ${{ inputs.version }} is not available"
          exit 1
        fi
      shell: bash

    - name: Install latest SQLite version
      if: inputs.version == ''
      run: |
        echo "No version specified, installing the latest version"
        sudo apt-get install -y sqlite3 libsqlite3-dev
        echo "Latest SQLite version installed successfully."
      shell: bash

    - name: Confirm SQLite installation
      run: |
        sqlite3 --version
        echo "SQLite has been successfully installed and is ready to use."
      shell: bash
