name: "Setup SQLite"

author: "ryohidaka <39184410+ryohidaka@users.noreply.github.com>"

description: "Custom action to set up SQLite environment."

branding:
  color: blue
  icon: database

inputs:
  version:
    description: "SQLite version to install (optional)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Check available SQLite versions
      id: check-versions
      run: |
        sudo apt-get update
        available_versions=$(apt-cache showpkg sqlite3 | grep -Eo '3\.[0-9]+\.[0-9]+' | sort -V | uniq | tr '\n' ',')
        available_versions=${available_versions%,}
        echo "Available versions: $available_versions"
        echo "versions=$available_versions" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache SQLite installation
      id: cache-sqlite
      uses: actions/cache@v4
      with:
        path: /usr/bin/sqlite3
        key: ${{ runner.os }}-sqlite-${{ inputs.version || 'latest' }}
        restore-keys: |
          ${{ runner.os }}-sqlite-

    - name: Check if SQLite is installed
      id: check-sqlite
      run: |
        if [ -f "/usr/bin/sqlite3" ]; then
          echo "SQLite is already installed."
          echo "skip_install=true" >> $GITHUB_OUTPUT
        else
          echo "SQLite is not installed."
          echo "skip_install=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Install specified SQLite version
      if: inputs.version != '' && steps.check-sqlite.outputs.skip_install == 'false'
      run: |
        if echo "${{ steps.check-versions.outputs.versions }}" | grep -q "^${{ inputs.version }}$"; then
          echo "Installing SQLite version ${{ inputs.version }}"
          sudo apt-get install -y sqlite3=${{ inputs.version }} libsqlite3-dev=${{ inputs.version }}
          echo "SQLite version ${{ inputs.version }} installed successfully."
        else
          echo "Error: Specified version ${{ inputs.version }} is not available"
          exit 1
        fi
      shell: bash

    - name: Install latest SQLite version
      if: inputs.version == '' && steps.check-sqlite.outputs.skip_install == 'false'
      run: |
        echo "No version specified, installing the latest version"
        sudo apt-get install -y sqlite3 libsqlite3-dev
        echo "Latest SQLite version installed successfully."
      shell: bash

    - name: Confirm SQLite installation
      run: |
        sqlite3 --version
        echo "SQLite has been successfully installed and is ready to use."
      shell: bash
