name: "Setup SQLite"

author: "ryohidaka <39184410+ryohidaka@users.noreply.github.com>"

description: "Custom action to set up SQLite environment."

branding:
  color: blue
  icon: database

inputs:
  version:
    description: "SQLite version to install (optional)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Check available SQLite versions
      id: check-versions
      run: |
        $GITHUB_ACTION_PATH/scripts/check_versions.sh
      shell: bash

    - name: Cache SQLite installation
      id: cache-sqlite
      uses: actions/cache@v4
      with:
        path: /usr/bin/sqlite3
        key: ${{ runner.os }}-sqlite-${{ inputs.version || 'latest' }}
        restore-keys: |
          ${{ runner.os }}-sqlite-

    - name: Check if SQLite is installed
      id: check-sqlite
      run: |
        $GITHUB_ACTION_PATH/scripts/cache_sqlite.sh
      shell: bash

    - name: Install specified SQLite version
      if: inputs.version != '' && steps.check-sqlite.outputs.skip_install == 'false'
      run: |
        $GITHUB_ACTION_PATH/scripts/install_version.sh "${{ inputs.version }}" "${{ steps.check-versions.outputs.versions }}"
      shell: bash

    - name: Install latest SQLite version
      if: inputs.version == '' && steps.check-sqlite.outputs.skip_install == 'false'
      run: |
        $GITHUB_ACTION_PATH/scripts/install_latest.sh
      shell: bash

    - name: Confirm SQLite installation
      run: |
        sqlite3 --version
        echo "SQLite has been successfully installed and is ready to use."
      shell: bash
