name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: ryohidaka/action-sh-format@v0.2.4
        with:
          path: "./scripts"
